baseURL = "https://wperron.io/"
languageCode = "en-us"
title = "William Perron"
author = "William Perron"
theme = "vitae"
uglyURLs = true
enableRobotsTXT = true
copyright = "&copy; Copyright 2020, William Perron"

[params]
  avatar = "/img/profile-small.jpg"
  subtitle = "Head in the clouds."
  [[params.social]]
    name = "GitHub"
    icon = "fab fa-github fa-1x"
    url = "https://github.com/wperron"
  [[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-1x"
    url = "https://twitter.com/_wperron"
  [[params.social]]
    name = "Resume"
    icon = "fas fa-file-pdf fa-1x"
    url = "https://docs.google.com/document/d/1s_cgwmFCmdYNhRfoymIbhstupZUUe13jfn0aW5bwcrQ/edit?usp=sharing"

[[menu.main]]
  name = "About"
  url = "/about.html"
  weight = -110
[[menu.main]]
  name = "Posts"
  url = "/posts.html"
  weight = -100
