baseURL = "https://wperron.io/"
languageCode = "en-us"
title = "William Perron"
author = "William Perron"
theme = "vitae"
uglyURLs = true
enableRobotsTXT = true
copyright = "&copy; Copyright 2020, William Perron"

[params]
  avatar = "/img/profile-small.jpg"
  subtitle = "I build stuff that works."
  [[params.social]]
    name = "GitHub"
    icon = "fab fa-github fa-1x"
    href = "https://github.com/wperron"
  [[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-1x"
    href = "https://twitter.com/_wperron"

[[menu.main]]
  name = "About"
  url = "/about.html"
  weight = -110
[[menu.main]]
  name = "Posts"
  url = "/posts.html"
  weight = -100
