# fly.toml file generated for wperron-io on 2022-05-19T10:44:27-04:00

app = "wperron-io"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[metrics]
port = 9091
path = "/metrics"

[env]
TZ = "America/New_York"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
